<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MioModLoader</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PolyHook2.NET" Version="1.1.3" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption 
        Include="System.Threading.ThreadPool.UseWindowsThreadPool" 
        Value="true" />
  </ItemGroup>
</Project>
